apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  #namespace: {{ .Values.settings.env }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/part-of: {{ include "name" . }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  addres-endpoint: {{ .Values.settings.adresEndpoint | quote }}
  brp-endpoint: {{ .Values.settings.brpEndpoint | quote }}
  verzoeken-endpoint: {{ .Values.settings.verzoekenEndpoint | quote }}
  verzoekType-endpoint: {{ .Values.settings.verzoekTypeEndpoint | quote }}
  processType-endpoint: {{ .Values.settings.processTypeEndpoint | quote }}
  webResource-endpoint: {{ .Values.settings.webResourceEndpoint | quote }}
  contract-endpoint: https://contracten-api-master-test.azurewebsites.net/api/personen/{bsn}/contracten
  digid-server: https://alsiam.s-hertogenbosch.nl/aselectserver/server
  digid-serverName: alsiam.s-hertogenbosch.nl
  digid-application-id: Denbosch_Verhuizen
  jwt-issuer: MijnApp

